/**
*  This code is part of the Harmony System implemented in Work Package 1 
*  of the Phosphorus project. This work is supported by the European 
*  Comission under the Sixth Framework Programme with contract number 
*  IST-034115.
*
*  Copyright (C) 2006-2009 Phosphorus WP1 partners. Phosphorus Consortium.
*  http://ist-phosphorus.eu/
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */


package org.opennaas.extensions.idb.da.dummy.webservice;

import org.apache.muse.core.AbstractCapability;
import org.w3c.dom.Element;

import org.opennaas.extensions.idb.da.dummy.handler.NotificationHandler;
import org.opennaas.extensions.idb.serviceinterface.notification.INotificationWS;

/**
 * nrpsDummyTopology server. MyCapability.java Thu Jun 26 10:38:49 CEST 2008
 * Generated by the Apache Muse Code Generation Tool
 */
public final class NotificationWS extends AbstractCapability implements
        INotificationWS {

    /**
     * Todo.
     */
    public Element addTopic(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "addTopic");
    }

    /**
     * Todo.
     */
    public Element getTopics(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "getTopics");
    }

    /**
     * Todo.
     */
    public Element publish(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "publish");
    }

    /**
     * Todo.
     */
    public Element removeTopic(final Element request) throws Exception {
        return NotificationHandler.getInstance()
                .handle(request, "removeTopic");
    }

    /**
     * Todo.
     */
    public Element subscribe(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "subscribe");
    }

    /**
     * Todo.
     */
    public Element unsubscribe(final Element request) throws Exception {
        return NotificationHandler.getInstance()
                .handle(request, "unsubscribe");
    }
}
