package eu.ist_phosphorus.harmony.common.serviceinterface.notification;

import org.apache.muse.ws.addressing.soap.SoapFault;
import org.w3c.dom.Element;

/**
 * notification client.
 *
 * INotificationClient.java
 * Mon Mar 05 12:58:49 CET 2012
 * Generated by the Apache Muse Code Generation Tool
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 /**
 * notification client.
 *
 */
 public interface INotificationClient {


    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
     Element getTopics (Element getTopics)
            throws SoapFault;


    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
     Element unsubscribe (Element unsubscribe)
            throws SoapFault;


    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
     Element removeTopic (Element removeTopic)
            throws SoapFault;


    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
     Element publish (Element publish)
            throws SoapFault;


    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
     Element addTopic (Element addTopic)
            throws SoapFault;


    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
     Element subscribe (Element subscribe)
            throws SoapFault;


}
