package org.opennaas.extensions.gmpls.webservice;

import org.w3c.dom.Element;

/**
 * reservation server.
 *
 * IMyCapability.java
 * Thu Oct 09 15:04:33 CEST 2008
 * Generated by the Apache Muse Code Generation Tool
 */
 public interface IMyCapability {
    String PREFIX = "tns";

    String NAMESPACE_URI = "http://ist_phosphorus.eu/gmpls/webservice";

    /**
     * getPathStatus Handler.
     *
     * @param getPathStatus Request
     * @return getPathStatus Response
     * @throws Exception In case of errors
     */
    public Element getPathStatus (Element getPathStatus)
            throws Exception;

    /**
     * getEndpointDiscovery Handler.
     *
     * @param getEndpointDiscovery Request
     * @return getEndpointDiscovery Response
     * @throws Exception In case of errors
     */
    public Element getEndpointDiscovery (Element getEndpointDiscovery)
            throws Exception;

    /**
     * getPathDiscovery Handler.
     *
     * @param getPathDiscovery Request
     * @return getPathDiscovery Response
     * @throws Exception In case of errors
     */
    public Element getPathDiscovery (Element getPathDiscovery)
            throws Exception;

    /**
     * createPath Handler.
     *
     * @param createPath Request
     * @return createPath Response
     * @throws Exception In case of errors
     */
    public Element createPath (Element createPath)
            throws Exception;

    /**
     * terminatePath Handler.
     *
     * @param terminatePath Request
     * @return terminatePath Response
     * @throws Exception In case of errors
     */
    public Element terminatePath (Element terminatePath)
            throws Exception;

}