package org.opennaas.extensions.gmpls.webservice;

import org.apache.muse.core.AbstractCapability;
import org.w3c.dom.Element;

import org.opennaas.extensions.gmpls.handler.NotificationHandler;
import org.opennaas.extensions.idb.serviceinterface.notification.INotificationWS;

/**
 * nrpsDummyTopology server.
 * 
 * MyCapability.java Thu Jun 26 10:38:49 CEST 2008 Generated by the Apache Muse
 * Code Generation Tool
 */
public class NotificationWS extends AbstractCapability implements
	INotificationWS {
    /*
     * (non-Javadoc)
     * 
     * @seeorg.opennaas.extensions.idb.serviceinterface.notification.
     * INotificationWS#addTopic(org.w3c.dom.Element)
     */
    public Element addTopic(Element request) throws Exception {
	return NotificationHandler.getInstance().handle(request, "addTopic");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeorg.opennaas.extensions.idb.serviceinterface.notification.
     * INotificationWS#getTopics(org.w3c.dom.Element)
     */
    public Element getTopics(Element request) throws Exception {
	return NotificationHandler.getInstance().handle(request, "getTopics");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeorg.opennaas.extensions.idb.serviceinterface.notification.
     * INotificationWS#publish(org.w3c.dom.Element)
     */
    public Element publish(Element request) throws Exception {
	return NotificationHandler.getInstance().handle(request, "publish");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeorg.opennaas.extensions.idb.serviceinterface.notification.
     * INotificationWS#removeTopic(org.w3c.dom.Element)
     */
    public Element removeTopic(Element request) throws Exception {
	return NotificationHandler.getInstance().handle(request, "removeTopic");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeorg.opennaas.extensions.idb.serviceinterface.notification.
     * INotificationWS#subscribe(org.w3c.dom.Element)
     */
    public Element subscribe(Element request) throws Exception {
	return NotificationHandler.getInstance().handle(request, "subscribe");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeorg.opennaas.extensions.idb.serviceinterface.notification.
     * INotificationWS#unsubscribe(org.w3c.dom.Element)
     */
    public Element unsubscribe(Element request) throws Exception {
	return NotificationHandler.getInstance().handle(request, "unsubscribe");
    }
}