/**
*  This code is part of the Harmony System implemented in Work Package 1 
*  of the Phosphorus project. This work is supported by the European 
*  Comission under the Sixth Framework Programme with contract number 
*  IST-034115.
*
*  Copyright (C) 2006-2009 Phosphorus WP1 partners. Phosphorus Consortium.
*  http://ist-phosphorus.eu/
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */


package eu.ist_phosphorus.harmony.translator.autobahn.webservice;

import org.apache.axis2.AxisFault;
import org.apache.log4j.Logger;
import org.apache.muse.core.AbstractCapability;
import org.apache.muse.ws.addressing.soap.SoapFault;
import org.w3c.dom.Element;

import eu.ist_phosphorus.harmony.common.serviceinterface.reservation.CommonReservationHandler;
import eu.ist_phosphorus.harmony.common.serviceinterface.reservation.IReservationWS;
import eu.ist_phosphorus.harmony.common.serviceinterface.topology.registrator.AbstractTopologyRegistrator;
import eu.ist_phosphorus.harmony.common.utils.PhLogger;
import eu.ist_phosphorus.harmony.translator.autobahn.handler.ReservationHandler;

/**
 * nrpsDummyReservation server. MyCapability.java Thu Jun 26 10:38:48 CEST 2008
 * Generated by the Apache Muse Code Generation Tool
 */
public class ReservationWS extends AbstractCapability implements IReservationWS {

    private CommonReservationHandler requestHandler = null;
    private final Logger logger = PhLogger.getLogger();

    /**
     * Default constructor that creates the ContextListener.
     * 
     * @throws AxisFault
     */
    public ReservationWS() throws AxisFault {
        if (AbstractTopologyRegistrator.getLatestInstance() == null) {
            new ContextListener();
        }
    }

    /**
     * activate Handler.
     * 
     * @param activate
     *            Request
     * @return activate Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element activate(final Element activate) throws SoapFault {
        return this.getHandler().handle(activate, "activate");
    }

    /**
     * bind Handler.
     * 
     * @param bind
     *            Request
     * @return bind Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element bind(final Element bind) throws SoapFault {
        return this.getHandler().handle(bind, "bind");
    }

    /**
     * cancelJob Handler.
     * 
     * @param cancelJob
     *            Request
     * @return cancelJob Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element cancelJob(final Element cancelJob) throws SoapFault {
        return this.getHandler().handle(cancelJob, "cancelJob");
    }

    /**
     * cancelReservation Handler.
     * 
     * @param cancelReservation
     *            Request
     * @return cancelReservation Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element cancelReservation(final Element cancelReservation)
            throws SoapFault {
        return this.getHandler().handle(cancelReservation, "cancelReservation");
    }

    /**
     * completeJob Handler.
     * 
     * @param completeJob
     *            Request
     * @return completeJob Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element completeJob(final Element completeJob) throws SoapFault {
        return this.getHandler().handle(completeJob, "completeJob");
    }

    /**
     * createReservation Handler.
     * 
     * @param createReservation
     *            Request
     * @return createReservation Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element createReservation(final Element createReservation)
            throws SoapFault {
        return this.getHandler().handle(createReservation, "createReservation");
    }

    /**
     * getFeatures Handler.
     * 
     * @param getFeatures
     *            Request
     * @return getFeatures Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element getFeatures(final Element getFeatures) throws SoapFault {
        return this.getHandler().handle(getFeatures, "getFeatures");
    }

    /**
     * Handler getter. Must not be in constructor!!
     * 
     * @return
     */
    private CommonReservationHandler getHandler() {
        if (null == this.requestHandler) {
            this.requestHandler = ReservationHandler.getInstance();
        }

        return this.requestHandler;
    }

    /**
     * getReservation Handler.
     * 
     * @param getReservation
     *            Request
     * @return getReservation Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element getReservation(final Element getReservation)
            throws SoapFault {
        return this.getHandler().handle(getReservation, "getReservation");
    }

    /**
     * getReservations Handler.
     * 
     * @param getReservations
     *            Request
     * @return getReservations Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element getReservations(final Element getReservations)
            throws SoapFault {
        return this.getHandler().handle(getReservations, "getReservations");
    }

    /**
     * getStatus Handler.
     * 
     * @param getStatus
     *            Request
     * @return getStatus Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element getStatus(final Element getStatus) throws SoapFault {
        this.logger.info("Invoking Reservation WS: get Status");
        return this.getHandler().handle(getStatus, "getStatus");
    }

    /**
     * isAvailable Handler.
     * 
     * @param isAvailable
     *            Request
     * @return isAvailable Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element isAvailable(final Element isAvailable) throws SoapFault {
        return this.getHandler().handle(isAvailable, "isAvailable");
    }

    /**
     * notification Handler.
     * 
     * @param notification
     *            Request
     * @return notification Response
     * @throws SoapFault
     *             In case of errors
     */
    public Element notification(final Element notification) throws SoapFault {
        return this.getHandler().handle(notification, "notification");
    }

}
