/**
*  This code is part of the Harmony System implemented in Work Package 1 
*  of the Phosphorus project. This work is supported by the European 
*  Comission under the Sixth Framework Programme with contract number 
*  IST-034115.
*
*  Copyright (C) 2006-2009 Phosphorus WP1 partners. Phosphorus Consortium.
*  http://ist-phosphorus.eu/
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */


package eu.ist_phosphorus.harmony.translator.g2mpls.webservice;

import org.apache.muse.core.AbstractCapability;
import org.w3c.dom.Element;

import eu.ist_phosphorus.harmony.common.serviceinterface.notification.INotificationWS;
import eu.ist_phosphorus.harmony.translator.g2mpls.handler.NotificationHandler;

/**
 * nrpsDummyTopology server.
 * 
 * MyCapability.java Thu Jun 26 10:38:49 CEST 2008 Generated by the Apache Muse
 * Code Generation Tool
 */
public class NotificationWS extends AbstractCapability implements
        INotificationWS {
    /*
     * (non-Javadoc)
     * 
     * @seeeu.ist_phosphorus.harmony.common.serviceinterface.notification.
     * INotificationWS#addTopic(org.w3c.dom.Element)
     */
    public Element addTopic(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "addTopic");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeeu.ist_phosphorus.harmony.common.serviceinterface.notification.
     * INotificationWS#getTopics(org.w3c.dom.Element)
     */
    public Element getTopics(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "getTopics");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeeu.ist_phosphorus.harmony.common.serviceinterface.notification.
     * INotificationWS#publish(org.w3c.dom.Element)
     */
    public Element publish(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "publish");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeeu.ist_phosphorus.harmony.common.serviceinterface.notification.
     * INotificationWS#removeTopic(org.w3c.dom.Element)
     */
    public Element removeTopic(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "removeTopic");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeeu.ist_phosphorus.harmony.common.serviceinterface.notification.
     * INotificationWS#subscribe(org.w3c.dom.Element)
     */
    public Element subscribe(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "subscribe");
    }

    /*
     * (non-Javadoc)
     * 
     * @seeeu.ist_phosphorus.harmony.common.serviceinterface.notification.
     * INotificationWS#unsubscribe(org.w3c.dom.Element)
     */
    public Element unsubscribe(final Element request) throws Exception {
        return NotificationHandler.getInstance().handle(request, "unsubscribe");
    }
}